### PR TITLE
Update Sphinx theme

### PR DESCRIPTION
**Pull request by arnaucasau**
### Summary
Updates to new Ecosystem theme.

For more information: https://github.com/Qiskit/qiskit_sphinx_theme/issues/232

### CODE REVIEW

**Comment by zlatko-minev** [comment]
This compiles ok on your end?

**Comment by arnaucasau** [comment]
Similar to #976. It has warning when running `tox -e docs`. The problem with this PR alone is the major increasing at the running time building the documentation. It takes locally 2 hours and a half. With the changes on #976 we can speed up the process to 16 minutes.

**Comment by zlatko-minev** [comment]
That should be merged now

**Comment by arnaucasau** [comment]
Great! Thank you @zlatko-minev!!

**Review by zlatko-minev — APPROVED** [review]

**Pull request merged**
