### PR TITLE
Move methods into class pages for docs

### PR DESCRIPTION
**Pull request by arnaucasau**
### Summary
Moved all the methods and attributes into class pages to speed up the building process of the documentation with the new ecosystem sphinx theme in https://github.com/qiskit-community/qiskit-metal/pull/975. The new theme increases the time building the documentation when we have a lot of pages, and with this PR we can achieve a major speedup.

See https://github.com/Qiskit/qiskit/pull/10455 for more information.

### CODE REVIEW

**Review by zlatko-minev — COMMENTED** [review]
Compiles ok on your end?

**Comment by arnaucasau** [comment]
Running `tox -e docs` locally it compiles and does what we expect, but it seems like it adds some extra warning to the ones that we can find in the main branch. I can fix them, but I was thinking of waiting until the CI in the main branch is fix to avoid mixing the warnings.

**Review by zlatko-minev — APPROVED** [review]
Ok, this can be merged now, what do you think?

**Comment by arnaucasau** [comment]
Yes :) With this PR merged we will be able to see a speed up building the documentation in #975

**Comment by arnaucasau** [comment]
@zlatko-minev I don't have write access to merge it. Can you do it when you have a moment, please? Thank you!!

**Pull request merged**
