### PR TITLE
Added multi-freq & broadband support. Added interpolation settings to freq sweep. All under `QHFSSDrivenmodalPyaedt`

### PR DESCRIPTION
**Pull request by clarkmiyamoto**
### What are the issues this pull addresses (issue numbers / links)?
https://github.com/Qiskit/qiskit-metal/issues/943

### Did you add tests to cover your changes (yes/no)?
No -  unsure how to add test for hfss freq sweep & setup.

### Did you update the documentation accordingly (yes/no)?
Yes

### Did you read the CONTRIBUTING document (yes/no)?
Yes

### Summary
All changes in `QHFSSDrivenmodalPyaedt`
- Exposed pyAEDT objects to front-end user on methods: `add_hfss_dm_setup` and `add_sweep`
- In `add_sweep` added support for interpolation settings
- In `add_hfss_dm_setup` added multi-frequency and broadband options for the front-end user.
- Documented changes in code & tutorial notebook `4\B\4.19\Drivenmodal...`

### CODE REVIEW

**Review by zlatko-minev — COMMENTED** [review]
Hi Clark, looks very nice, great job, have you checked that these work well when you run the code?

**Comment by clarkmiyamoto** [comment]
@zlatko-minev hey! just caught a bug in the `add_hfss_dm_setup` thanks for making me double check haha. Everything is good now

**Comment by zlatko-minev** [comment]
Great job!

**Review by zlatko-minev — APPROVED** [review]
LGTM, Great work

**Comment by clarkmiyamoto** [comment]
hey @zlatko-minev hope you're doing well. Was wondering if there's anything preventing these changes from being merged? Lmk and thanks!

**Comment by zlatko-minev** [comment]
Thank you, @clarkmiyamoto ! Planning to merge

**Pull request merged**
