### PR TITLE
Add missing gui styles when installing

### LINKED ISSUE #1006: Missing gui styles
### Information

- **Qiskit Metal version**: 0.1.5
- **Python version**: 3.10.11
- **Operating system**: Windows 11

### What is the current behavior?
When installing with `pip` the default styles of the gui are missing (the folder `_gui/styles` is not copied in the installed package)
We even have an error message in the console of the gui `gui2: Could not find the stylesheet file where expected c:\Users\account\Python_venv\qiskit-metal-10\lib\site-packages\qiskit_metal\_gui\styles\metal_dark\style.qss [main_window_base._load_stylesheet_from_file]`

### Steps to reproduce the problem
`pip install qiskit-metal`

### What is the expected behavior?
Having two default styles for the gui: "Metal Dark" and "Q Dark"

### Suggested solutions
Copy the missing folder during the installation

### PR DESCRIPTION
**Pull request by PositroniumJS**
### What are the issues this pull addresses (issue numbers / links)?
Fix #1006

### Did you add tests to cover your changes (yes/no)?
No need

### Did you update the documentation accordingly (yes/no)?
No need

### Did you read the CONTRIBUTING document (yes/no)?
Yes

### Summary
Add missing gui styles when installing with pip and fix some typos

### Details and comments
Add missing gui styles when installing with pip and fix some typos

### CODE REVIEW

**Comment by zlatko-minev** [comment]
Have you checked this runs ok in practice? No errors

**Comment by PositroniumJS** [comment]
> Have you checked this runs ok in practice? No errors

Yes, in the installed package folder you get a `styles` directory containing for each style the file `style.qss` and the directory `rc` with all its photos

**Review by zlatko-minev — APPROVED** [review]

**Comment by zlatko-minev** [comment]
Wonderful job, thank you. This all looks pretty good to me

**Comment by zlatko-minev** [comment]
Can you take a look at #1002 , this will be a major update. I will try to merge these changes into that. I want to make sure that #1002 works for you. I hope to merge it in the next week or two.

**Pull request merged**
